import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Board DnD</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="w-4/5 mx-auto block py-5">
				<h1 className="text-xl text-center font-bold">Board DnD</h1>
				<p className="text-center">
					<i>A simple drag and drop apps for project management</i>
				</p>
			</div>
		</div>
	);
};

export default Home;
